import './globals.css'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import Link from 'next/link'

import { Header } from '@/components/header'
import { Toaster } from '@/components/ui/sonner'

import { Providers } from './providers'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-w-screen w-screen h-screen min-h-screen`}
      >
        <Providers>
          <Header />
          {children}

          <span className="fixed text-zinc-950 dark:text-zinc-50 font-semibold text-xs bottom-4 left-1/2 -translate-x-1/2 z-50">
            developed by{' '}
            <Link
              href="https://github.com/pedroaba"
              rel="search"
              className="hover:underline"
              target="_blank"
            >
              pedr.augustobarbosa.aparecido@gmail.com
            </Link>
          </span>

          <Toaster richColors position="top-center" closeButton />
        </Providers>
      </body>
    </html>
  )
}
